<?php

namespace Rahi\ApiBundle\Entity\Repository\Account\PhoneNumber;

/**
 * PhoneNumberTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneNumberTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
