<?php

namespace Rahi\ApiBundle\Entity\Repository\Lottery;

/**
 * MetricTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetricTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
