<?php

namespace Rahi\ApiBundle\Entity\Repository\Lottery;

use Doctrine\ORM\EntityRepository;

/**
 * NumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WinningNumberRepository extends EntityRepository
{
}
