<?php

namespace Rahi\ApiBundle\Entity\Repository\Locale;

/**
 * LocaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocaleRepository extends \Doctrine\ORM\EntityRepository
{
}
