<?php

namespace Rahi\ApiBundle\Entity\Repository\Locale;

/**
 * ProvinceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvinceRepository extends \Doctrine\ORM\EntityRepository
{
}
