<?php

namespace Rahi\ApiBundle\Entity\Repository\Locale;

/**
 * TimezoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimezoneRepository extends \Doctrine\ORM\EntityRepository
{
}
