<?php

namespace Rahi\ApiBundle\Entity\Repository\Locale\Address;

/**
 * AddressTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
