<?php

namespace Rahi\ApiBundle\Entity\Repository\Locale\Region;

/**
 * RegionItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionItemRepository extends \Doctrine\ORM\EntityRepository
{
}
