<?php

namespace Rahi\ApiBundle\Entity\Repository\Locale\Region;

/**
 * RegionItemTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionItemTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
